// MVP starter profanity blocklist for player names.
// This is an adapted, intentionally limited subset to get baseline moderation in place.
// Replace/expand with a vetted upstream list (for example LDNOOBW / naughty-words) before public scale.

export const BLOCKED_TERMS = [
  "anal",
  "anus",
  "arse",
  "asshole",
  "bastard",
  "bitch",
  "blowjob",
  "bollock",
  "boner",
  "boob",
  "buttplug",
  "clit",
  "cock",
  "condom",
  "coon",
  "crap",
  "cum",
  "cunt",
  "damn",
  "dick",
  "dildo",
  "dyke",
  "fag",
  "faggot",
  "fellatio",
  "fuck",
  "fucker",
  "goddamn",
  "handjob",
  "hentai",
  "horny",
  "jackoff",
  "jizz",
  "kike",
  "masturbat",
  "milf",
  "motherfucker",
  "nazi",
  "nigger",
  "orgasm",
  "penis",
  "piss",
  "porn",
  "prick",
  "pussy",
  "rape",
  "rapist",
  "retard",
  "shit",
  "slut",
  "spic",
  "suicide",
  "tit",
  "tits",
  "twat",
  "vagina",
  "wank",
  "whore",
];

// Names reserved for system/admin-looking impersonation and abuse reduction.
export const BLOCKED_EXACT_NAMES = [
  "admin",
  "administrator",
  "cloudflare",
  "moderator",
  "mod",
  "owner",
  "staff",
  "support",
  "system",
];
